<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="primo_arm">

  <!-- Parameters -->
  <xacro:property name="link_length" value="0.1"/>
  <xacro:property name="link_radius" value="0.02"/>

  <!-- Colors -->
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>

  <!-- Macro for link and joint -->
  <xacro:macro name="dynamixel_link" params="index parent child length radius xyz rpy axis">
    <joint name="joint_${index}" type="revolute">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="${axis}"/>
      <limit effort="1.0" lower="-3.14" upper="3.14" velocity="1.0"/>
    </joint>

    <link name="${child}">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.05"/>
      </geometry>
      <material name="gray"/>
    </visual>
  </link>

  <!-- Arm chain -->
  <xacro:dynamixel_link index="1" parent="base_link" child="link_1" length="${link_length}" radius="${link_radius}" xyz="0 0 0.02" rpy="0 0 0" axis="0 0 1"/>
  <xacro:dynamixel_link index="2" parent="link_1" child="link_2" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="1 0 0"/>
  <xacro:dynamixel_link index="3" parent="link_2" child="link_3" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="0 1 0"/>
  <xacro:dynamixel_link index="4" parent="link_3" child="link_4" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="1 0 0"/>
  <xacro:dynamixel_link index="5" parent="link_4" child="link_5" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="0 1 0"/>
  <xacro:dynamixel_link index="6" parent="link_5" child="link_6" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="1 0 0"/>
  <xacro:dynamixel_link index="7" parent="link_6" child="link_7" length="${link_length}" radius="${link_radius}" xyz="0 0 ${link_length}" rpy="0 0 0" axis="0 1 0"/>

</robot>

